### PR TITLE
Fix for the trie stage failure

### PR DESCRIPTION
**Pull request by AlexeyAkhunov**

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
Oh, will try to dive into this problem now, otherwise hard to review

**Comment by AskAlexSharov** [comment]
This func - is final step after couple others:
```
_preOrderTraversalStepNoInDepth - nextSiblingInMem || nextSiblingOfParentInMem || nextSiblingInDB
```
It means: 
```
Imagine that last prefix we returned was: 
050f0f0f0f06 (c.prev = 050f0f0f0f06, c.k[c.lvl] = 050f0f0f0f, c.childID[c.lvl] = 6) 

Now we need do step forward
- nextSiblingInMem - will check if any siblings in current parent exists 050f0f0f0f*
- if no, then nextSiblingOfParentInMem - will check if any siblings of any parents exists 050f0f0f*, 050f0f*, 050f*, 05*
- if no, then nextSiblingInDB - will go to next sibling is DB, and after last step we are on node "05" 
- means: c.prev = 050f0f0f0f06, c.k[c.lvl] = 05 

In my understanding c.next in this case must be: 06, but not 050f0f0f0f07 (but it will have same effect, because nextSiblingInMem and nextSiblingOfParentInMem checked that db has no records after 050f0f0f0f06 with prefix 05*).
```

So, I have no confidence that this fix actually changing something. 
If you can reproduce problem - please try to run `./cmd/integration state_stages --integrity.fast=true --integrity.slow=true` on failing block - maybe integrity checks will catch that Trie bucket has wrong data (and bug is on write side).

**Comment by AlexeyAkhunov** [comment]
I think I understand it now. The table is missing one of the intermediate hashes it is supposed to have. It has `07`, then `080b`, but there is no `08` for some reason. That's why the error happens, and the algorithm tries to feed `080b07` into `GenStructStep` multiple times

**Comment by AlexeyAkhunov** [comment]
That's the entire bucket, BTW:
```
00 120000000000
01 84a000000000
03 080400000000
05 020800000000
06 028000000000
07 208000000000
080b 0884000000800ec408a60bb4a8d41105c120e483622ee05c1c97120f637217ab8e69d93011ab
09 0d0100000000
0a 00b00000008005718fda6375d0bc50d511410dfe41d2884b04625ccac54ec8cbf4a95b0033fb
0b 120000000000
0c 001200000000
0d 505000000000
0f 018400000000
```

**Comment by AlexeyAkhunov** [comment]
And that's the full `PlainState` bucket:
```
000000064730640b7d670408d74280924883064f 02088ac7230489e80000
004385d8be6140e6f889833f68b51e17b6eacb29 03011708423271ba114c2340
03d60763cfe40d907640fd52ef5787beaf8eee9e 02084563918244f40000
0893315bf8ac38b74eed7caa7e5c67c6edd1f3e7 0501010101
10f5d45854e038071485ac9e402308cf80d2d2fe 02084563918244f40000
27a5f9fae7fdb948a7efa71da5f90e479fc110bc 0501010101
3221055c2d8569a931509332e4ed0d4a307bf966 0501010101
36267c845cc42b57ccb869d655e5d5fb620cc69a 02081df11f840e9d610e
388ea662ef2c223ec0b047d41bf3c0f362142ad5 02084563918244f40000
38fb9488031f36553adf0c380e1b272efa9f0f2c 0501010101
4aee49638568e355162c6c849e92470f281518ce 02084563918244f40000
4e078052e09f4aeae3a337ce9986e041879994f9 0501010101
60adc0f89a41af237ce73554ede170d733ec14e0 020a130ee8e7179044400000
627306090abab3a6e1400e9345bc60c78a8bef57 0301020a130e425e60f1887921c8
71a921615eb9645eaacd57be1c9927a82b97d4e3 02084563918244f40000
7b364c0bf5579a39647fe2e19b6e00697b6aa9af 02084563918244f40000
8b2f527a7bb63f326a0b586fa1b8da3ef8d0999e 0501010101
8f250e11d90daf4cbc0fc47f9f2d3a6e267bcdee 02084563918244f40000
99a848f6d8bb6d6cd1a524b3c99a97e41e1e4b5a 02084563918244f40000
a47efa8ff326b3aaa4f1a39e76865123341d0ff7 02084563918244f40000
a6eb9f54a8bfb38ebb7bb6b460dfa4d126d0d708 0501010101
aa074419fd6fa9c65f3049bfb7d02a0755d20533 0501010101
b8c3bffb71f76bee2b2f81bdbc53ad4c43e3f58e 020a130ee8e7179044400000
badc0de9e0794b049b5ea63c3e1e698a3476c172 030202b408456a696b93614978
c3298c6341f82468309302611e24d3003bc79b46 0208ebec21ee1da40000
c3298c6341f82468309302611e24d3003bc79b47 02084563918244f40000
c3298c6341f82468309302611e24d3003bc79b48 02084563918244f40000
c3298c6341f82468309302611e24d3003bc79b49 02084563918244f40000
c3298c6341f82468309302611e24d3003bc79b50 02084563918244f40000
c3298c6341f82468309302611e24d3003bc79b51 02084563918244f40000
c3298c6341f82468309302611e24d3003bc79b52 02084563918244f40000
c3298c6341f82468309302611e24d3003bc79b53 02084563918244f40000
c3298c6341f82468309302611e24d3003bc79b60 02084563918244f40000
dba3ed3db9d2907daaf924fad1c66d1ed92bf7f8 0f01010105010120e3e50b8d763481b5d5c534b35954555653bc59afde42c7353b54b6389fa38bed
dba3ed3db9d2907daaf924fad1c66d1ed92bf7f800000000000000010000000000000000000000000000000000000000000000000000000000000000 07
dba3ed3db9d2907daaf924fad1c66d1ed92bf7f800000000000000010000000000000000000000000000000000000000000000000000000000000001 07
dba3ed3db9d2907daaf924fad1c66d1ed92bf7f800000000000000010000000000000000000000000000000000000000000000000000000000000002 0c
df0a88b2b68c673713a8ec826003676f272e3573 02084563918244f40000
edf80c46d6926ca3c7e588af7006a436fd4afc5f 0501010101
f17f52151ebef6c7334fad080c5704d77216b732 020a130ee8e7179044400000
f84943ce9e4653e9fc1f2c453509d8921748d255 0501010101
fb7afd6a0ddbe8ad651f05c15f140d36ca3299e8 02084563918244f40000
fe3b557e8fb62b89f4916b721be55ceb828dbd73 0301200a1308255edb5e12968210
```

**Pull request closed without merging**
