### PR TITLE
Move compatibility check

### PR DESCRIPTION
**Pull request by AlexeyAkhunov**

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
Next code will block call until connection ready:
```
		versionReply, err := db.remoteKV.Version(ctx, &emptypb.Empty{}, grpc.WaitForReady(true))
```
It means we can spawn goroutine to check version. 
And if check doesn't match - cancel root context (or just write to logs).

**Comment by AlexeyAkhunov** [comment]
> Next code will block call until connection ready:
> 
> ```
> 		versionReply, err := db.remoteKV.Version(ctx, &emptypb.Empty{}, grpc.WaitForReady(true))
> ```
> 
> It means we can spawn goroutine to check version.
> And if check doesn't match - cancel root context (or just write to logs).

Ok, I am happy for you to do alternative or just modify this branch

**Comment by AlexeyAkhunov** [comment]
> versionReply, err := db.remoteKV.Version(ctx, &emptypb.Empty{}, grpc.WaitForReady(true))

I am going to test your solution

**Comment by AskAlexSharov** [comment]
Something like this? https://github.com/ledgerwatch/turbo-geth/compare/version_check?expand=1

**Comment by AlexeyAkhunov** [comment]
> Something like this? https://github.com/ledgerwatch/turbo-geth/compare/version_check?expand=1

Yes, I have done very similar thing, but not for EthBackend. If it passes, I will merge this PR, and then you can extend to EthBackend

**Pull request merged**
