### PR TITLE
Remove changeset-based decorators from WalkAsOf

### PR DESCRIPTION
**Pull request by AlexeyAkhunov**
These decorators were supposed to deal with the situations when history index is out of sync with the changesets. Now this situation can only happen during the initial sync, so decorators can be removed. It should also fix https://github.com/ledgerwatch/turbo-geth/issues/1275

### CODE REVIEW

**Comment by tjayrush** [comment]
I reran the curl commands that were failing before for issue #1275.

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "debug_accountRange", "params": [10000000, "AAAAAAAAAAAAAAAAAAAAAAACFRQ=", 1, true, true, true], "id":1}' localhost:8545
```

and 

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "debug_accountRange", "params": [10000000, "", 0, false, false, false], "id":1}' localhost:8545
```
They both still fail with the same result returned to `curl`:

```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}}
```

And the same error reported in the daemon:

```
ERROR[11-17|10:39:46.424] RPC method debug_accountRange crashed: runtime error: slice bounds out of range [:20] with capacity 8
```

**Comment by AlexeyAkhunov** [comment]
Yes, it appears to be the artefact of the data - will figure out what it is. I will still do code simplification

**Comment by AlexeyAkhunov** [comment]
There is indeed a "stray" value in my database in the `AccountHistoryIndex` table, with the key `a71a110000000000`. Normally, the keys in this table should be 28 bytes (not 8 bytes) long

**Comment by tjayrush** [comment]
I think it may have been like that for a while. A couple of weeks ago, I was trying to debug issue #1275, and I became so confused I buckled under...now that I think about it, I think it was because of 8 bytes when the code seemed to want more.

**Comment by AlexeyAkhunov** [comment]
Now I have looked through the database and could not find any keys with the length of 8 bytes, all of them are 28 bytes as expected. Which leads me to believe that the bug is in the remote KV communication

**Comment by AlexeyAkhunov** [comment]
Looks like accountRange works now. I will need to fix the tests before merging this in

**Pull request merged**
