### PR TITLE
optimize codeBitmap

### PR DESCRIPTION
**Pull request by JekaMas**
It introduces `JumpDests` LRU bucked cache

### CODE REVIEW

**Comment by AlexeyAkhunov** [comment]
Hmm, I am a bit puzzled on why this change needs such a complex infrastructure - global pooling (I would not like it to proliferate this pattern, but rather reduce it, because it will make migration harder), chunking, replacing bitvec with some seemingly more complex ByteBuffer structure, your own LRU implementation with garbage collection? In the end, you just place the cache inside the vmConfig. I thought it would be just a simple LRU cache (could have used hashicorp one, for example) for bitvectors (you could have changed bitvec to be based on `[]uint64` instead of `[]byte`, for example).
The main complexity of this optimisation is to decide where to place the cache. Not sure the vmConfig is the right place for it either. Would be better to have something separate, like currently gasPool.

**Comment by JekaMas** [comment]
@AlexeyAkhunov  I've removed custom LRU. vmConfig was chosen because it seems more or less suitable and it's present in Contract type, I didn't want to introduce new field into EVM and Contract.

**Comment by AlexeyAkhunov** [comment]
Thank you! What is the advantage of using `ByteBuffer` over `bitvec`? I thought that once the bitmap is constructed, it is immutable, so I do not see the reason for the buffer

**Comment by JekaMas** [comment]
We use ByteBuffer quite a lot and as far as `type bitvec []byte` I decided to reuse it. Technically, it's the same []byte as it was.

**Comment by AlexeyAkhunov** [comment]
Ok, thank you. I still think that putting a cache inside the config object is wrong, and it should be passed separately

**Comment by AlexeyAkhunov** [comment]
I think you could avoid a lot of changes in the tests if you make destCache optional (it probably already is), and you don't really need to pass it around in the chain_maker and all the tests. Otherwise I see how it turns into quite a lot of work

**Pull request merged**
