### PR TITLE
rpcdaemon performance improve - less reading blocks, less allocs on server

### PR DESCRIPTION
**Pull request by AskAlexSharov**
For: 
https://github.com/ledgerwatch/turbo-geth/issues/1421
and 
https://github.com/ledgerwatch/turbo-geth/issues/1422

### CODE REVIEW

**Comment by MysticRyuujin** [comment]
FWIW: This appears to be quite a bit faster, perhaps > 2x faster

tg:
tg

rpcdaemon:
rpcdaemon

**Comment by AskAlexSharov** [comment]
Thank you for profiling pictures. 
I see on RPCDaemon profiling - that we creating too much cursors (cursorInit calls).
Added change to reduced amount of cursors.

**Comment by MysticRyuujin** [comment]
Here's an update:
rpcdaemon2

**Comment by AskAlexSharov** [comment]
@MysticRyuujin is performance of this branch good enough or not?

**Comment by MysticRyuujin** [comment]
The update did appear to be slightly faster. It's still quite a bit slower than Geth, but is it "good enough?" probably :slightly_smiling_face: 

When doing `versus --concurrency=2` I get something like 202.70 per second vs 1056.83 per second (tg is 5.2x slower). When doing `versus --concurrency=40` I get 1685.49 per second vs 9803.24 per second (tg is 5.8x slower).

These are on different hardware, but the TG hardware should be faster. I know the architecture is different, so maybe it can't be helped?

I'm happy with over 2x improvement vs the original tests though!

**Comment by AlexeyAkhunov** [comment]
We can also test it in the shared memory mode (with `--chaindata` option instead of `--private.addr` option)

**Pull request merged**
