### PR TITLE
grpc regenerate

### LINKED ISSUE #935: net_version method crashed
Hi there,

Tried to check new net_version and it crashed

#### System information

OS & Version: Linux
Commit hash : 09440dccd3e73b17ca3ab6cc7decf9a29544b3a8 (HEAD -> master, origin/master, origin/HEAD)

#### Expected behaviour
Retrieve version number

#### Actual behaviour
```
$ ./build/bin/rpcdaemon --chaindata ~/.local/share/turbogeth/tg/chaindata/ --http.api=eth,debug,net
INFO [08-17|16:24:40.855] HTTP endpoint opened                     url=http://localhost:8545
ERROR[08-17|16:24:50.639] RPC method net_version crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 28 [running]:
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call.func1(0xc0000d1a53, 0xb, 0xc0002f4cf8)
	github.com/ledgerwatch/turbo-geth@/rpc/service.go:200 +0xb5
panic(0xf59880, 0x19b9470)
	runtime/panic.go:679 +0x1b2
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*NetAPIImpl).Version(0xc0000c5e40, 0x128af40, 0xc0001c8a40, 0x0)
	github.com/ledgerwatch/turbo-geth@/cmd/rpcdaemon/commands/net_version.go:8 +0x29
reflect.Value.call(0xc000032d80, 0xc0000d48e8, 0x13, 0x10c26f8, 0x4, 0xc000167740, 0x2, 0x2, 0xc0002f4b70, 0x465d5c, ...)
	reflect/value.go:460 +0x5f6
reflect.Value.Call(0xc000032d80, 0xc0000d48e8, 0x13, 0xc000167740, 0x2, 0x2, 0x0, 0x0, 0x0)
	reflect/value.go:321 +0xb4
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc000032de0, 0x128af40, 0xc0001c8a40, 0xc0000d1a53, 0xb, 0x1af7e80, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ledgerwatch/turbo-geth@/rpc/service.go:206 +0x2b9
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc00011c5a0, 0x128af40, 0xc0001c8a40, 0xc0000f2d90, 0xc000032de0, 0x1af7e80, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:389 +0x8a
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc00011c5a0, 0xc0001673b0, 0xc0000f2d90, 0x42dbee)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:337 +0x298
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc00011c5a0, 0xc0001673b0, 0xc0000f2d90, 0x1276f01)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:298 +0x1f3
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleMsg.func1(0xc0001673b0)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:139 +0x46
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc00011c5a0, 0xc0000e1fe0)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:226 +0x119
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:222 +0x66

WARN [08-17|16:24:50.639] Served net_version                       conn=172.28.0.10:38020 reqid=26401 t="131.303µs" err="method handler crashed"
```

### PR DESCRIPTION
**Pull request by JekaMas**
my bad @akme , I forgot to push my last commit.

Thank you for patience and testing!

closes #935

### CODE REVIEW

**Comment by akme** [comment]
> my bad @akme , I forgot to push my last commit.
> 
> Thank you for patience and testing!
> 
> closes #935

I made changes from this commit to my local repo, but it still crashes
```
ERROR[08-17|21:03:27.021] RPC method net_version crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 94 [running]:
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call.func1(0xc0001e8603, 0xb, 0xc00010ecf8)
	github.com/ledgerwatch/turbo-geth@/rpc/service.go:200 +0xb5
panic(0xf59880, 0x19b9470)
	runtime/panic.go:679 +0x1b2
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*NetAPIImpl).Version(0xc00018f2e0, 0x128af40, 0xc0005d8900, 0x0)
	github.com/ledgerwatch/turbo-geth@/cmd/rpcdaemon/commands/net_version.go:8 +0x29
reflect.Value.call(0xc000438900, 0xc000010a30, 0x13, 0x10c26f8, 0x4, 0xc00045e540, 0x2, 0x2, 0xc00010eb70, 0x465d5c, ...)
	reflect/value.go:460 +0x5f6
reflect.Value.Call(0xc000438900, 0xc000010a30, 0x13, 0xc00045e540, 0x2, 0x2, 0x0, 0x0, 0x0)
	reflect/value.go:321 +0xb4
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc000438960, 0x128af40, 0xc0005d8900, 0xc0001e8603, 0xb, 0x1af7e80, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ledgerwatch/turbo-geth@/rpc/service.go:206 +0x2b9
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc000246870, 0x128af40, 0xc0005d8900, 0xc00036c310, 0xc000438960, 0x1af7e80, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:389 +0x8a
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc000246870, 0xc0000bdce0, 0xc00036c310, 0x42dbee)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:337 +0x298
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc000246870, 0xc0000bdce0, 0xc00036c310, 0x1276f01)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:298 +0x1f3
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleMsg.func1(0xc0000bdce0)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:139 +0x46
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc000246870, 0xc000524100)
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:226 +0x119
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
	github.com/ledgerwatch/turbo-geth@/rpc/handler.go:222 +0x66
```

**Comment by JekaMas** [comment]
Have you recompiled tg and RPCDeamon? I ask because I've checked it twice before the push and it worked fine.

**Comment by JekaMas** [comment]
I test it like that:
```
make tg
make rpcdeamon

./build/bin/tg --private.api.addr=0.0.0.0:9090
./build/bin/rpcdaemon --private.api.addr=localhost:9090 --http.api=eth,debug,net

curl -X POST -H "Content-Type: application/json"   --data '{"jsonrpc":"2.0","method":"net_version", "params": [], "id":1}' localhost:8545
```

**Comment by akme** [comment]
Yes, this curl request crashes method handler. Maybe I copied something wrong, will wait for merge and retest.

**Comment by akme** [comment]
What I did last:
1. Updated golang to 1.15
2. Switched branch to  regenerate-net-version
```
$ git show
commit c138b53ec339046f31f1b6662562cf0864268e8c (HEAD -> regenerate-net-version, origin/regenerate-net-version)
Author: Evgeny Danienko <6655321@bk.ru>
Date:   Mon Aug 17 23:46:25 2020 +0300

    grpc regenerate
```
2. Recompiled tg
3. Recompiled rcpdaemon
4. Sent request with curl
5. Method crashed

**Comment by JekaMas** [comment]
Hmm... Let me check once again, going change testing steps a bit:
0. remove old tg, rpcdeamon binaries, ensure that tg, rpcdeamon commands are not exist
1. The same as it was

Could you also try it?

**Comment by akme** [comment]
Removed and rebuilt:
```
$ make rpcdaemon
env GO111MODULE=on go run build/ci.go install ./cmd/rpcdaemon
./cmd/rpcdaemon
>>> /usr/lib/go-1.15/bin/go build -ldflags -X main.gitCommit=c138b53ec339046f31f1b6662562cf0864268e8c -X main.gitDate=20200817 -trimpath -v -o /home/ubuntu/turbo-geth/build/bin/rpcdaemon ./cmd/rpcdaemon
Done building.
Run "./build/bin/rpcdaemon" to launch rpcdaemon.
$ make tg
env GO111MODULE=on go run build/ci.go install ./cmd/geth
./cmd/geth
>>> /usr/lib/go-1.15/bin/go build -ldflags -X main.gitCommit=c138b53ec339046f31f1b6662562cf0864268e8c -X main.gitDate=20200817 -trimpath -v -o /home/ubuntu/turbo-geth/build/bin/tg ./cmd/geth
Done building.
Run "./build/bin/tg" to launch turbo-geth.
```
Same crash

**Comment by akme** [comment]
Found out that when I add  `--private.api.addr=localhost:9090` method doesn't crash, but doesn't work either:
```
ERROR[08-18|09:07:43.117] NetVersion call got an error             err="rpc error: code = Unavailable desc = connection closed"
```
or
```
ERROR[08-18|09:08:13.923] NetVersion call got an error             err="rpc error: code = Unavailable desc = timed out waiting for server handshake"
```

**Comment by akme** [comment]
While it gives an error, also it returns response:
```
{"jsonrpc":"2.0","id":1,"result":0}
```
But the result should be a string:
```
Aug 18 11:29:47.631 WARN Trying again after net_version RPC call failed (attempt #17780) with result Err(Decoder("Error(\"invalid type: number, expected a string\", line: 0, column: 0)"))
```

**Comment by JekaMas** [comment]
Just to check, have you added `-http.api=eth,debug,net` flag to your `rpcdeamon`? If you haven't mentioned `net` API it won't work.
@akme

**Comment by akme** [comment]
> Just to check, have you added `-http.api=eth,debug,net` flag to your `rpcdeamon`? If you haven't mentioned `net` API it won't work.
> @akme

yes, I did

**Comment by JekaMas** [comment]
Could you provide your full commands for tg and RPCDeamon?

**Comment by akme** [comment]
> Could you provide your full commands for tg and RPCDeamon?
```
$ ./build/bin/tg
```
```
$ ./build/bin/rpcdaemon --chaindata ~/.local/share/turbogeth/tg/chaindata/ --http.api=eth,debug,net --http.addr 127.0.0.1
```

**Comment by JekaMas** [comment]
Thank you @akme I've restored meaningful error message if rpcDeamon can't get data from tg.
In normal case `tg --private.api.addr=0.0.0.0:9090` + `rpcdaemon --private.api.addr=localhost:9090 --http.api=eth,debug,net` should work fine.

**Comment by akme** [comment]
> Thank you @akme I've restored meaningful error message if rpcDeamon can't get data from tg.
> In normal case `tg --private.api.addr=0.0.0.0:9090` + `rpcdaemon --private.api.addr=localhost:9090 --http.api=eth,debug,net` should work fine.

```
ERROR[08-18|12:55:03.705] Could not create listener                address=0.0.0.0:9090 err="listen tcp 0.0.0.0:9090: bind: address already in use"
```
they can't share the same port
also when I add private.api I can't get any block data
After add private.api as you mentioned I still get
```
ERROR[08-18|12:55:31.155] NetVersion call got an error             err="rpc error: code = Unavailable desc = connection closed"
```

**Comment by JekaMas** [comment]
The posr is already has listener that's why RPCDeamon can't call tg node, just change 9090 port to any free and suitable for you.

**Comment by akme** [comment]
> The post is already has listener that's why RPCDeamon can't call tg node, just change 9090 port to any free and suitable for you.

Changed ports, but behavior is the same
```
ERROR[08-18|13:05:40.164] NetVersion call got an error             err="rpc error: code = Unavailable desc = connection closed"
```
and can't get block data
```
WARN [08-18|13:05:16.821] Served eth_getBlockByNumber              conn=127.0.0.1:37914 reqid=1 t="224.513µs" err="block not found: 0"
```
without --private.api flags eth_getBlockByNumber is working

**Comment by JekaMas** [comment]
```
./build/bin/tg --private.api.addr=0.0.0.0:9095
./build/bin/rpcdaemon --private.api.addr=localhost:9095 --http.api=eth,debug,net
```

```
curl --data '{"method":"eth_getBlockByNumber","params":["0x1b4", true],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545

{"jsonrpc":"2.0","id":1,"result":{"difficulty":"0x4ea3f27bc","extraData":"0x476574682f4c5649562f76312e302e302f6c696e75782f676f312e342e32","gasLimit":"0x1388","gasUsed":"0x0","hash":"0xdc0818cf78f21a8e70579cb46a43643f78291264dda342ae31049421c82d21ae","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0xbb7b8287f3f0a933474a79eae42cbca977791171","mixHash":"0x4fffe9ae21f1c9e15207b1f472d5bbdd68c9595d461666602f2be20daf5e7843","nonce":"0x689056015818adbe","number":"0x1b4","parentHash":"0xe99e022112df268087ea7eafaf4790497fd21dbeeb6bd7a1721df161a6657a54","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x220","stateRoot":"0xddc8b0234c2e0cad087c8b389aa7ef01f7d79b2570bccb77ce48648aa61c904d","timestamp":"0x55ba467c","totalDifficulty":8310116004413,"transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]}}
```

```
curl -X POST -H "Content-Type: application/json"   --data '{"jsonrpc":"2.0","method":"net_version", "params": [], "id":426}' localhost:8545

{"jsonrpc":"2.0","id":426,"result":1}
```
```

**Comment by akme** [comment]
> ```
> ./build/bin/tg --private.api.addr=0.0.0.0:9095
> ./build/bin/rpcdaemon --private.api.addr=localhost:9095 --http.api=eth,debug,net
> ```
> 
> ```
> curl --data '{"method":"eth_getBlockByNumber","params":["0x1b4", true],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
> 
> {"jsonrpc":"2.0","id":1,"result":{"difficulty":"0x4ea3f27bc","extraData":"0x476574682f4c5649562f76312e302e302f6c696e75782f676f312e342e32","gasLimit":"0x1388","gasUsed":"0x0","hash":"0xdc0818cf78f21a8e70579cb46a43643f78291264dda342ae31049421c82d21ae","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0xbb7b8287f3f0a933474a79eae42cbca977791171","mixHash":"0x4fffe9ae21f1c9e15207b1f472d5bbdd68c9595d461666602f2be20daf5e7843","nonce":"0x689056015818adbe","number":"0x1b4","parentHash":"0xe99e022112df268087ea7eafaf4790497fd21dbeeb6bd7a1721df161a6657a54","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x220","stateRoot":"0xddc8b0234c2e0cad087c8b389aa7ef01f7d79b2570bccb77ce48648aa61c904d","timestamp":"0x55ba467c","totalDifficulty":8310116004413,"transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]}}
> ```
> 
> ```
> curl -X POST -H "Content-Type: application/json"   --data '{"jsonrpc":"2.0","method":"net_version", "params": [], "id":426}' localhost:8545
> 
> {"jsonrpc":"2.0","id":426,"result":1}
> ```

that worked, looks like --chaindata flag for rpcdaemon was an issue, thanks !
But what about returning string instead of int in result reponse?

**Comment by JekaMas** [comment]
I've checked Ethereum API https://eth.wiki/json-rpc/API and it looks like it should be a string.

**Comment by akme** [comment]
> I've checked Ethereum API https://eth.wiki/json-rpc/API and it looks like it should be a string.

Yeap, but now it returns an integer, will you fix this?

**Comment by JekaMas** [comment]
I've just pushed the commit :)

**Comment by akme** [comment]
Tested, working, thanks! =)

**Comment by JekaMas** [comment]
Thank you for your help!

**Pull request merged**
