### PR TITLE
Clean tmp on start

### PR DESCRIPTION
**Pull request by AskAlexSharov**

### CODE REVIEW

**Comment by AlexeyAkhunov** [comment]
Is it always desired? I remember we have some logic to handle migrations from temp files. Maybe this needs to happen after migration was successful?

**Comment by AskAlexSharov** [comment]
Maybe more make sense to move migrations folder from:
<datadir>/etl-tmp/migrations
to 
<datadir>/migrations 
?

**Comment by AskAlexSharov** [comment]
And rename: `<datadir>/etl-tmp` to `<datadir>/yes-you-can-remove-me` :-)

**Comment by AlexeyAkhunov** [comment]
> Maybe more make sense to move migrations folder from:
> `<datadir>/etl-tmp/migrations`
> to
> `<datadir>/migrations`
> ?

Not sure. These are also ETL files :) And I know some people are already mounting `etl-tmp` to different disks. So we will pull a rug under them (but only if we do another large re-writing migration in the future)

**Comment by AskAlexSharov** [comment]
My wife can sell them rug

**Comment by AskAlexSharov** [comment]
I still think move migrations folder is good idea, because when people asking us "can I remove etl-tmp folder?" we tell them - yes.

**Pull request merged**
