### PR TITLE
Use stage name as db key

### PR DESCRIPTION
**Pull request by AskAlexSharov**
For: https://github.com/ledgerwatch/turbo-geth/issues/855

### CODE REVIEW

**Comment by AlexeyAkhunov** [comment]
We might need to use migrations to get people who already synced seamlessly upgrade: https://github.com/ledgerwatch/turbo-geth/tree/master/migrations

**Comment by AlexeyAkhunov** [comment]
We used to call it in the `eth/backend.go`, but I removed it recently. Perhaps need to put it back: https://github.com/ledgerwatch/turbo-geth/commit/7bc45fab80e6db063697e47e49437c99bc8a3b91#diff-e42690942282286ede9e53bbe7b0c248

**Comment by mandrigin** [comment]
@AlexeyAkhunov I think in that case it is trivial to figure out if we store a number of a string

**Comment by AskAlexSharov** [comment]
Database migrations: 

### Created new bucket dbutils.Migrations 
Format: migrationName -> cbor serialized SyncStageProgress and SyncStageUnwind buckets
It stores stages progress to understand in which context was executed migration
in case of bug-report developer can ask content of this bucket 

### Best Practices

From `./migrations/migrations.go` docs:
```
migrations apply sequentially in order of this array, skips applied migrations
it allows - don't worry about merge conflicts and use switch branches
see also dbutils.Migrations - it stores context in which each transaction was exectured - useful for bug-reports

Idempotency is expected
Best practices to achieve Idempotency:
- in dbutils/bucket.go add suffix for existing bucket variable, create new bucket with same variable name.
	Example:
		- SyncStageProgress = []byte("SSP1")
		+ SyncStageProgressOld1 = []byte("SSP1")
		+ SyncStageProgress = []byte("SSP2")
- clear new bucket in the begining of transaction, drop old bucket in the end (not defer!).
	Example:
		Up: func(db ethdb.Database, datadir string, OnLoadCommit etl.LoadCommitHandler) error {
			if err := db.(ethdb.NonTransactional).ClearBuckets(dbutils.SyncStageProgress); err != nil { // clear new bucket
				return err
			}

			extractFunc := func(k []byte, v []byte, next etl.ExtractNextFunc) error {
				... // migration logic
			}
			if err := etl.Transform(...); err != nil {
				return err
			}

			if err := db.(ethdb.NonTransactional).DropBuckets(dbutils.SyncStageProgressOld1); err != nil {  // clear old bucket
				return err
			}
		},
- if you need migrate multiple buckets - create separate migration for each bucket
- write test for new transaction
````

### Drop old Bucket
LMDB has limitation for amount of buckets, means need delete old buckets.
`common/dbutils/bucket.go` - has new array `DeprecatedBuckets` - list of buckets which can be programmatically deleted - for example after migration.
drop happening out out of ETL transaction (maybe doable move it inside)

**Comment by AlexeyAkhunov** [comment]
Good stuff!

you are doing MarshallAllStages to keep the staged information in memory while the migrations are happening? Isn't this specific to the migrations that change the stages but not to the migrations that, for example, introduce dupSort?
or you did not it for simplicity, just in case any migration changes stages?

**Comment by AskAlexSharov** [comment]
content of dbutils.Migration bucket is not related to my task. It saves stages - just to make it possible later reproduce problems (if somebody coming with bug-report we may ask to send us this bucket). 
So, you will know when user executed migration. In our architecture "when" means - not timestamp and not block number but progress of all stages

**Comment by AskAlexSharov** [comment]
Added a bit more tests, added migrations to `./cmd/integrations` (as precondition to all commands)

**Pull request merged**
